spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/dev/h2/db/wpob
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true

jwt:
  secret: bi2DBsHDSpToYCTFSRxmGgfqaxuVNhRN8P1RpI84PxwrSF2ChP