spring:
  datasource:
    url: ${db.url}
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${db.username}
    password: ${db.password}
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        show_sql: false
        format_sql: false
    database: mysql
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect

jwt:
  secret: ${jwt.secret}